// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: eye_of_god.proto
#ifndef GRPC_eye_5fof_5fgod_2eproto__INCLUDED
#define GRPC_eye_5fof_5fgod_2eproto__INCLUDED

#include "eye_of_god.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace eye_grpc {

class IFS_SourceData final {
 public:
  static constexpr char const* service_full_name() {
    return "eye_grpc.IFS_SourceData";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Add(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::eye_grpc::AddResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::AddResponse>> AsyncAdd(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::AddResponse>>(AsyncAddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::AddResponse>> PrepareAsyncAdd(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::AddResponse>>(PrepareAsyncAddRaw(context, request, cq));
    }
    virtual ::grpc::Status ImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::eye_grpc::FeatureResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::FeatureResponse>> AsyncImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::FeatureResponse>>(AsyncImgFeatureRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::FeatureResponse>> PrepareAsyncImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::FeatureResponse>>(PrepareAsyncImgFeatureRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Add(::grpc::ClientContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Add(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::eye_grpc::AddResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Add(::grpc::ClientContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void Add(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::eye_grpc::AddResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void ImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ImgFeature(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::eye_grpc::FeatureResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void ImgFeature(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::eye_grpc::FeatureResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::AddResponse>* AsyncAddRaw(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::AddResponse>* PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::FeatureResponse>* AsyncImgFeatureRaw(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::eye_grpc::FeatureResponse>* PrepareAsyncImgFeatureRaw(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Add(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::eye_grpc::AddResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::eye_grpc::AddResponse>> AsyncAdd(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::eye_grpc::AddResponse>>(AsyncAddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::eye_grpc::AddResponse>> PrepareAsyncAdd(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::eye_grpc::AddResponse>>(PrepareAsyncAddRaw(context, request, cq));
    }
    ::grpc::Status ImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::eye_grpc::FeatureResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::eye_grpc::FeatureResponse>> AsyncImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::eye_grpc::FeatureResponse>>(AsyncImgFeatureRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::eye_grpc::FeatureResponse>> PrepareAsyncImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::eye_grpc::FeatureResponse>>(PrepareAsyncImgFeatureRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Add(::grpc::ClientContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response, std::function<void(::grpc::Status)>) override;
      void Add(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::eye_grpc::AddResponse* response, std::function<void(::grpc::Status)>) override;
      void Add(::grpc::ClientContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void Add(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::eye_grpc::AddResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void ImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response, std::function<void(::grpc::Status)>) override;
      void ImgFeature(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::eye_grpc::FeatureResponse* response, std::function<void(::grpc::Status)>) override;
      void ImgFeature(::grpc::ClientContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void ImgFeature(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::eye_grpc::FeatureResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::eye_grpc::AddResponse>* AsyncAddRaw(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::eye_grpc::AddResponse>* PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::eye_grpc::SourceData& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::eye_grpc::FeatureResponse>* AsyncImgFeatureRaw(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::eye_grpc::FeatureResponse>* PrepareAsyncImgFeatureRaw(::grpc::ClientContext* context, const ::eye_grpc::Source_image& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Add_;
    const ::grpc::internal::RpcMethod rpcmethod_ImgFeature_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Add(::grpc::ServerContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response);
    virtual ::grpc::Status ImgFeature(::grpc::ServerContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Add() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd(::grpc::ServerContext* context, ::eye_grpc::SourceData* request, ::grpc::ServerAsyncResponseWriter< ::eye_grpc::AddResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ImgFeature : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ImgFeature() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ImgFeature() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImgFeature(::grpc::ServerContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestImgFeature(::grpc::ServerContext* context, ::eye_grpc::Source_image* request, ::grpc::ServerAsyncResponseWriter< ::eye_grpc::FeatureResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Add<WithAsyncMethod_ImgFeature<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Add() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::eye_grpc::SourceData, ::eye_grpc::AddResponse>(
          [this](::grpc::ServerContext* context,
                 const ::eye_grpc::SourceData* request,
                 ::eye_grpc::AddResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Add(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_Add(
        ::grpc::experimental::MessageAllocator< ::eye_grpc::SourceData, ::eye_grpc::AddResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::eye_grpc::SourceData, ::eye_grpc::AddResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Add(::grpc::ServerContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ImgFeature : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_ImgFeature() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::eye_grpc::Source_image, ::eye_grpc::FeatureResponse>(
          [this](::grpc::ServerContext* context,
                 const ::eye_grpc::Source_image* request,
                 ::eye_grpc::FeatureResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->ImgFeature(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_ImgFeature(
        ::grpc::experimental::MessageAllocator< ::eye_grpc::Source_image, ::eye_grpc::FeatureResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::eye_grpc::Source_image, ::eye_grpc::FeatureResponse>*>(
          ::grpc::Service::experimental().GetHandler(1))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ImgFeature() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImgFeature(::grpc::ServerContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ImgFeature(::grpc::ServerContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Add<ExperimentalWithCallbackMethod_ImgFeature<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Add() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ImgFeature : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ImgFeature() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ImgFeature() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImgFeature(::grpc::ServerContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Add() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ImgFeature : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_ImgFeature() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ImgFeature() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImgFeature(::grpc::ServerContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestImgFeature(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Add() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Add(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Add(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ImgFeature : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_ImgFeature() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->ImgFeature(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_ImgFeature() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImgFeature(::grpc::ServerContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ImgFeature(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Add() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::eye_grpc::SourceData, ::eye_grpc::AddResponse>(std::bind(&WithStreamedUnaryMethod_Add<BaseClass>::StreamedAdd, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Add(::grpc::ServerContext* context, const ::eye_grpc::SourceData* request, ::eye_grpc::AddResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAdd(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::eye_grpc::SourceData,::eye_grpc::AddResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ImgFeature : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ImgFeature() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::eye_grpc::Source_image, ::eye_grpc::FeatureResponse>(std::bind(&WithStreamedUnaryMethod_ImgFeature<BaseClass>::StreamedImgFeature, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ImgFeature() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ImgFeature(::grpc::ServerContext* context, const ::eye_grpc::Source_image* request, ::eye_grpc::FeatureResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedImgFeature(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::eye_grpc::Source_image,::eye_grpc::FeatureResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Add<WithStreamedUnaryMethod_ImgFeature<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Add<WithStreamedUnaryMethod_ImgFeature<Service > > StreamedService;
};

}  // namespace eye_grpc


#endif  // GRPC_eye_5fof_5fgod_2eproto__INCLUDED
